[package]
name = "Web-Client"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "curl"
path = "src/main.rs"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
url = "2.2"
structopt = "0.3"
serde_json = "1.0"